export const initialStateOfDesignContext = {
  state: '',
  setState: () => {},
  currentComponent: null,
  setCurrentComponent: () => {},
  color: '',
  setColor: (value: string) => {},
  image: '',
  setImage: (value: string) => {},
  rotate: 0,
  setRotate: (value: number) => {},
  width: '',
  setWidth: (value: string) => {},
  height: '',
  setHeight: (value: string) => {},
  left: '',
  setLeft: (value: string) => {},
  top: '',
  setTop: (value: string) => {},
  padding: '',
  setPadding: (value: string) => {},
  fontSize: '',
  setFontSize: (value: string) => {},
  fontWeight: '',
  setFontWeight: (value: string) => {},
  opacity: '',
  setOpacity: (value: string) => {},
  text: '',
  setText: (value: string) => {},
  zIndex: '',
  setZIndex: (value: string) => {},
  radius: 0,
  setRadius: (value: number) => {},
  components: [],
  setComponents: ([]: any[]) => {},
  show: { status: true, name: '' },
  setShow: () => {},
  updateCurrentComponentProperties: () => {},
  moveElement: () => {},
  resizeElement: () => {},
  rotateElement: () => {},
  createShape: () => {},
  addImage: () => {},
  addText: () => {},
  removeComponent: () => {},
  removeBackground: () => {},
  opacityHandler: (e) => {},
  setElements: (type: string, shape: string) => {},
};