export const initialStateOfDesignContext = {
  state: '',
  setState: () => {},
  currentComponent: null,
  setCurrentComponent: () => {},
  color: '',
  setColor: () => {},
  image: '',
  setImage: () => {},
  rotate: 0,
  setRotate: () => {},
  width: '',
  setWidth: () => {},
  height: '',
  setHeight: () => {},
  left: '',
  setLeft: () => {},
  top: '',
  setTop: () => {},
  padding: '',
  setPadding: () => {},
  fontSize: '',
  setFontSize: () => {},
  fontWeight: '',
  setFontWeight: () => {},
  opacity: '',
  setOpacity: () => {},
  text: '',
  setText: () => {},
  zIndex: '',
  setZIndex: () => {},
  radius: 0,
  setRadius: () => {},
  components: [],
  setComponents: () => {},
  show: { status: true, name: '' },
  setShow: () => {},
  updateCurrentComponentProperties: () => {},
  moveElement: () => {},
  resizeElement: () => {},
  rotateElement: () => {},
  createShape: () => {},
  addImage: () => {},
  addText: () => {},
  removeComponent: () => {},
  removeBackground: () => {},
  opacityHandler: () => {},
  setElements: () => {},
};